package app.striclub.pojo.stepAndIngriedients

data class Post(
        val post_id: String,
        val user_id: String,
        val headline: String,
        val content: String,
        val post_image: String,
        val category: String,
        val no_like: String,
        val no_comment: String,
        val no_share: String,
        val no_fb_share: String,
        val created: String,
        val link: String,
        val post_type: String,
        val source: String,
        val is_reported: String,
        val news_id: String,
        val title: String,
        val news_content: String,
        val news_image: String,
        val url: String,
        val blog_id: String,
        val image: String,
        val image1: String,
        val image2: String,
        val image3: String,
        val state: String,
        val city: String,
        val username: String,
        val uimage: String,
        val Isliked: String,
        val IsSavedpost: String
)